#include <iostream>
#include <set>
#include <unordered_map>

#include "../Problems.h"
#include "../Problem.h"
#include "../BigInteger.h"
#include "../String.h"

using namespace std;

void P29() {
    AddProblem(
        {
            29, "How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?",

            []() -> string {

                //map<pair<int, int>, bool> done;
                set<BigInteger> values;
                set<double> v;
                vector<double> all;
                unordered_map<double, bool> m;
                for (int a = 2; a <= 100; a++)
                {
                    for (int b = 2; b <= 100; b++)
                    {
                        //SortedSet set = new SortedSet();

                        for (int a = 2; a <= 100; a++) {
                            for (int b = 2; b <= 100; b++) {
                                double result = pow(a, b);
                                m[result] = true;
                                //v.insert(result);
                                //all.push_back(result);
                            }
                        }
                       // BigInteger value(to_string(a));
                        //cout << value.GetNumber() << endl;
                        //value.Pow(b);
                        //cout << endl;
                        //cout << a << "^" << b << " = " << value << endl;
                        //values.insert(value); 
                        //for (auto &i : values) {
                        //    cout << i << " ";
                        //}
                        //cout << endl;
                    }
                }
                
               // cout << endl;
                //int answer = m.size(); // (int)v.size();
                int answer = m.size();
                cout << answer << endl;
                return to_string(answer);
            }
        });
};