#include <iostream>
#include <set>
#include <unordered_map>

#include "../Problems.h"
#include "../Problem.h"
#include "../BigInteger.h"
#include "../String.h"

using namespace std;

void P29() {
    AddProblem(
        {
            29, "How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?",

            []() -> string {

                //map<pair<int, int>, bool> done;
                set<BigInteger> values;
                unordered_map<double, bool> m;

                for (int a = 2; a <= 100; a++) {
                    for (int b = 2; b <= 100; b++) {
                        double result = pow(a, b);
                        m[result] = true;
                    }
                }
                
                return to_string(m.size());
            }
        });
};